name: PHPUnit and Code Linting

on:
  push:
    branches:
      - master
      - staging
      - feature/*
  pull_request:
    branches:
      - master
      - staging
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-suggest --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Perform Code Style Fixes
        run: ./vendor/bin/pint

      - name: Create Database
        run: |
                mkdir -p database
                touch database/database.sqlite


      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test --parallel

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/reports/junit.xml
